language: node_js

services:
  - docker

install:
  - docker build -t millercollin07/nm1 .
  - docker run -d -p 5000:5000 millercollin07/nm1 
script:
  - docker ps -a

deploy:
  docker push millercollin07/nm1
